--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-05-27 18:00:42

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 4880 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16484)
-- Name: aluno; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.aluno (
    id bigint NOT NULL,
    cpf character varying(255),
    email character varying(255),
    nome character varying(255)
);


ALTER TABLE public.aluno OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16483)
-- Name: aluno_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.aluno ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aluno_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16589)
-- Name: disciplina; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.disciplina (
    id bigint NOT NULL,
    carga_horaria integer,
    nome character varying(255),
    professor_id bigint
);


ALTER TABLE public.disciplina OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16588)
-- Name: disciplina_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.disciplina ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.disciplina_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16600)
-- Name: matricula_aluno; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.matricula_aluno (
    id bigint NOT NULL,
    nota1 double precision,
    nota2 double precision,
    status character varying(255),
    aluno_id bigint,
    disciplina_id bigint,
    CONSTRAINT matricula_aluno_status_check CHECK (((status)::text = ANY ((ARRAY['MATRICULADO'::character varying, 'APROVADO'::character varying, 'REPROVADO'::character varying, 'TRANCADO'::character varying])::text[])))
);


ALTER TABLE public.matricula_aluno OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16599)
-- Name: matricula_aluno_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.matricula_aluno ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matricula_aluno_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16581)
-- Name: professor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.professor (
    id bigint NOT NULL,
    cpf character varying(255),
    email character varying(255),
    nome character varying(255)
);


ALTER TABLE public.professor OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16580)
-- Name: professor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.professor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.professor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4868 (class 0 OID 16484)
-- Dependencies: 218
-- Data for Name: aluno; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.aluno (id, cpf, email, nome) FROM stdin;
6	123.123.123-12	aime@gmail.com	Aimê
7	123.123.123-12	aime@gmail.com	Clayton D'Amore
8	123.123.123-45	Ford68@yahoo.com	Jill O'Hara
9	123.456.789-01	blue@gmail.com	Bruno Henrique
\.


--
-- TOC entry 4872 (class 0 OID 16589)
-- Dependencies: 222
-- Data for Name: disciplina; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.disciplina (id, carga_horaria, nome, professor_id) FROM stdin;
1	60	BackEnd	1
2	60	FrontEnd	3
3	60	BancoDeDados	4
\.


--
-- TOC entry 4874 (class 0 OID 16600)
-- Dependencies: 224
-- Data for Name: matricula_aluno; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.matricula_aluno (id, nota1, nota2, status, aluno_id, disciplina_id) FROM stdin;
2	7.5	9	APROVADO	7	2
1	5.5	6	REPROVADO	6	1
3	10	6.5	APROVADO	8	3
\.


--
-- TOC entry 4870 (class 0 OID 16581)
-- Dependencies: 220
-- Data for Name: professor; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.professor (id, cpf, email, nome) FROM stdin;
1	123.123.123-18	Makenzie_Jacobi@gmail.com	Joe Padberg
3	123.123.123-18	Raul56@gmail.com	Dr. Ann McDermott
4	123.123.123-18	Helmer.Lowe@yahoo.com	Lucas Pacocha
2	123.123.123-18	Milan.Weimann@yahoo.com	Raul Lehner III
\.


--
-- TOC entry 4881 (class 0 OID 0)
-- Dependencies: 217
-- Name: aluno_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.aluno_id_seq', 9, true);


--
-- TOC entry 4882 (class 0 OID 0)
-- Dependencies: 221
-- Name: disciplina_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.disciplina_id_seq', 3, true);


--
-- TOC entry 4883 (class 0 OID 0)
-- Dependencies: 223
-- Name: matricula_aluno_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.matricula_aluno_id_seq', 3, true);


--
-- TOC entry 4884 (class 0 OID 0)
-- Dependencies: 219
-- Name: professor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.professor_id_seq', 5, true);


--
-- TOC entry 4712 (class 2606 OID 16579)
-- Name: aluno aluno_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.aluno
    ADD CONSTRAINT aluno_pkey PRIMARY KEY (id);


--
-- TOC entry 4716 (class 2606 OID 16593)
-- Name: disciplina disciplina_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.disciplina
    ADD CONSTRAINT disciplina_pkey PRIMARY KEY (id);


--
-- TOC entry 4718 (class 2606 OID 16605)
-- Name: matricula_aluno matricula_aluno_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matricula_aluno
    ADD CONSTRAINT matricula_aluno_pkey PRIMARY KEY (id);


--
-- TOC entry 4714 (class 2606 OID 16587)
-- Name: professor professor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.professor
    ADD CONSTRAINT professor_pkey PRIMARY KEY (id);


--
-- TOC entry 4720 (class 2606 OID 16611)
-- Name: matricula_aluno fk4mtt3iew11xcs5i7tshj7la9q; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matricula_aluno
    ADD CONSTRAINT fk4mtt3iew11xcs5i7tshj7la9q FOREIGN KEY (disciplina_id) REFERENCES public.disciplina(id);


--
-- TOC entry 4721 (class 2606 OID 16606)
-- Name: matricula_aluno fkn1iea49e3kxfecd5e27i7lvak; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matricula_aluno
    ADD CONSTRAINT fkn1iea49e3kxfecd5e27i7lvak FOREIGN KEY (aluno_id) REFERENCES public.aluno(id);


--
-- TOC entry 4719 (class 2606 OID 16594)
-- Name: disciplina fkoqie7f1kx32b1atco9fpgxd7g; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.disciplina
    ADD CONSTRAINT fkoqie7f1kx32b1atco9fpgxd7g FOREIGN KEY (professor_id) REFERENCES public.professor(id);


-- Completed on 2025-05-27 18:00:43

--
-- PostgreSQL database dump complete
--

